config/routes.rb
Lacaze::Application.routes.draw do
 
  resources :bookings

 
  root to: 'static_pages#home'
  
  match '/directions',      to: 'static_pages#directions'
  match '/instructions',    to: 'static_pages#instructions'
  match '/things_to_do',    to: 'static_pages#things_to_do'
  match '/taxis',           to: 'static_pages#taxis'
  match '/pool',            to: 'static_pages#pool'
  match '/autumn_spring',   to: 'static_pages#autumn_spring'
  match '/photos',          to: 'static_pages#photos'
  match '/help',            to: 'static_pages#help'
  match '/contact',         to: 'static_pages#contact'  
  match '/bookings',        to: 'bookings#index'  
  match '/new_booking',     to: 'bookings#new'  
  match '/edit_booking',     to: 'bookings#edit'  
  match '/delete_booking',     to: 'bookings#destroy'  
  match '/edit_or_delete_booking',     to: 'bookings#edit_or_delete'  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :end, :name, :start

  validates :name,  presence: true
  validates :start, presence: true
  validates :end, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @booking.start = params[:start]
    #end
  end

  def edit
    @booking = Booking.find(params[:id])
    render 'edit'
  end

  def create
    @booking = Booking.new(params[:booking])
    if @booking.save
      flash[:success] = "Booking saved"
      @bookings = Booking.all
      render 'index'
    else
      render 'new'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update_attributes(params[:booking])
      flash[:success] = "Booking updated"
      @bookings = Booking.all
      render 'index'
    else
      render 'edit'
    end
  end

  def index
    @bookings = Booking.all
  end

  def destroy
    b = Booking.find(params[:id])
    b.destroy
    flash[:success] = "Booking removed."
    @bookings = Booking.all
    render 'index'
  end

  def edit_or_delete
    @booking = Booking.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def directions
  end

  def instructions
  end

  def things_to_do
  end

  def pool
  end

  def autumn_spring
  end

  def help
  end

  def photos
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Lacaze"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bookings/edit.html.erb
<% provide(:title, 'Edit Booking') %>
<style>
p.padding
{
padding-top:50px;
}
</style>


<h1>Edit booking</h1>

<%= render 'layouts/new_edit_booking' %>  

app/views/bookings/edit_or_delete.html.erb
<% provide(:title, 'Edit or Delete Booking') %>

<body>
	<h1>
		Edit or delete booking
	</h1>
	 <div id="centered-inline">
	 	<%= link_to "<button class = 'btn btn-large btn-primary'>Edit</button>".html_safe, edit_booking_path(@booking.id), :id => "button_id" %>
	 	<%= link_to "<button class = 'btn btn-large btn-danger'>Delete</button>".html_safe, { :action => "destroy", :id => @booking.id, }, :method => "delete", data: { confirm: "You sure?" } %>
	</div>
</body>

app/views/bookings/index.html.erb
<% provide(:title, 'Bookings') %>

<script type='text/javascript'>


    $(document).ready(function() {   

    
        var calendar = $('#calendar').fullCalendar({
            header: {
                left: 'today',
                center: 'title',
                right: 'prevYear,prev next,nextYear'
            },
            selectable: true,
            selectHelper: true,
            dayClick: function(start, end, allDay) {
                var startAsString = getDayName(start)+" "+start.getDate()+" "+getMonthName(start)+" "+start.getFullYear()
                location.href = "<%=new_booking_path%>?start="+startAsString             
             },
            editable: true,
            disableDragging: false,
            events: [
                <% @bookings.each do |booking| %>
                    {
                    title: '<%= booking.name %>',
                    start: new Date('<%= booking.start %>'),
                    end:   new Date('<%= booking.end %>'),
                    url:   '<%= edit_or_delete_booking_path :id => booking.id%>' 
                    },
                <% end %>
            ],
         });    

        <% if (@booking != nil) %>
        $('#calendar').fullCalendar('gotoDate', <%=@booking.start.year%>, <%=@booking.start.month-1%>);
        <%end%>       
    });

    function getDayName(date){
        var day_names = new Array ( );
        day_names[day_names.length] = "Sunday";
        day_names[day_names.length] = "Monday";
        day_names[day_names.length] = "Tuesday";
        day_names[day_names.length] = "Wednesday";
        day_names[day_names.length] = "Thursday";
        day_names[day_names.length] = "Friday";
        day_names[day_names.length] = "Saturday";
        return day_names[date.getDay()]
    } 

    function getMonthName(date) {
        var month_names = new Array ( );
        month_names[month_names.length] = "January";
        month_names[month_names.length] = "February";
        month_names[month_names.length] = "March";
        month_names[month_names.length] = "April";
        month_names[month_names.length] = "May";
        month_names[month_names.length] = "June";
        month_names[month_names.length] = "July";
        month_names[month_names.length] = "August";
        month_names[month_names.length] = "September";
        month_names[month_names.length] = "October";
        month_names[month_names.length] = "November";
        month_names[month_names.length] = "December";
        return month_names[date.getMonth()]
    }
 
</script>
<style type='text/css'>

    body {
        margin-top: 40px;
        text-align: center;
        font-size: 14px;
        font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
        }

    #calendar {
        width: 600px;
        margin: 0 auto;
        }
</style>
</head>
<body>
    <h1>
        Bookings for:
    </h1>
    <div id='calendar'>
    </div>
    <div>
        Click on a start date to make a new booking
        </br>
        Click on a booking to edit or delete it.
    </div>
</body>
</html>

app/views/bookings/new.html.erb
<% provide(:title, 'New Booking') %>
<style>
p.padding
{
padding-top:50px;
}
</style>


<h1>New booking</h1>

<%= render 'layouts/new_edit_booking' %>  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Last modified: 10th April 2014
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Lacaze", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li class = "dropdown">
            <a id="travel" class="dropdown-toggle" data-toggle="dropdown" href="#">
              Travel
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="directions" role="menu">
              <li><%= link_to "Directions",     directions_path %></li>
              <li><%= link_to "Toulonjac Map", "http://www.map-france.com/Toulonjac-12200/map-Toulonjac.html"%></li>
              <li><%= link_to "Taxis",   taxis_path %></li>
            </ul>
          </li>
          <li><%= link_to "Instructions",   instructions_path %></li>
          <li><%= link_to "Activities",   things_to_do_path %></li>
          <li><%= link_to "Pool", pool_path %></li>
          <li><%= link_to "Autumn/Spring", autumn_spring_path %></li>
          <li class = "dropdown">
            <a id="bookings" class="dropdown-toggle" data-toggle="dropdown" href="#">
              Bookings
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="bookings" role="menu">
              <li><%= link_to "All bookings",  bookings_path %></li>
              <li><%= link_to "New booking",  new_booking_path %></li>
            </ul>
          </li>
          <li><%= link_to "Photos",   photos_path %></li>
          <li><%= link_to "HELP",           help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_new_edit_booking.html.erb
<script>
  $(document).ready(function(){
    $("#booking_start").datepicker({  dateFormat: "DD d MM yy" });
    $("#booking_end").datepicker  ({  dateFormat: "DD d MM yy" });
  })
</script>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@booking) do |f| %>
      <% if @booking.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-error">
            The form contains <%= pluralize(@booking.errors.count, "error") %>.
          </div>
          <ul>
            <% @booking.errors.full_messages.each do |msg| %>
              <li>* <%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :start %>
      <input type="text"  id='booking_start' name="booking[start]" 
          value= "<%= !@booking.nil? && !@booking.start.nil? ? @booking.start.strftime('%A %-d %B %Y'):nil  %>" 
      /> 

      <%= f.label :end %>
      <input type="text"  id='booking_end' name="booking[end]" 
          value= "<%= !@booking.nil? ? 
                          !@booking.end.nil? ? @booking.end.strftime('%A %-d %B %Y') : 
                              !@booking.start.nil? ? @booking.start.strftime('%A %-d %B %Y') : nil
                          : nil 
                          %>" 
      />

      <p class="padding">Save the booking      
        <%= f.submit "Save", class: "btn btn-large btn-primary" %>
      </p>
    <% end %>
    <%= link_to "<button class = 'btn btn-large'>Cancel</button>".html_safe, bookings_path%>
  </div>
</div>

app/views/layouts/_print.html.erb
 <div class="print-page">
    <%= link_to image_tag("printer.png", :size => "25x25", :alt => "PRINT"), '#', onclick: "window.print()"%>
 </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/autumn_spring.html.erb
<% provide(:title, 'Autumn/Spring') %>
<h1>Autumn/Spring</h1>
<%= render 'layouts/print' %> 
<h2>In advance</h2>

<h3>Pool</h3> 
<ul>
	<li>See below</li> 
</ul>
<h3>Phone</h3> 
<ul>
    <li>Cancel the phone</li> 
    <li>Cancel the internet</li> 
</ul>
<h3>Kitchen</h3> 
<ul> 
    <li>Clean the main fridge of perishable food; defrost both fridges</li> 
    <li>Put perishable food in storage tins</li> 
</ul>
<h3>Sofas</h3> 
<ul> 
    <li>Cover sofas with plastic/dust sheets</li> 
</ul>
<h3>Mice</h3> 
<ul> 
    <li>Put down mouse bait</li> 
</ul>
<h3>Garden</h3> 
<ul> 
    <li>Bring comfy loungers into the house</li> 
    <li>Bring BBQ into house and store by the stove</li> 
    <li>Close up the storage cupboard under the stairs and the pool store</li> 
    <li>Store pots under the hedge</li> 
    <li>Hide the wheelbarrow</li> 
    <li>Bring in the clothes line</li> 
</ul>
<h2>Leaving</h2>
<h3>Water</h3> 
<ul> 
    <li>Take reading</li> 
    <li>Drain the plumbing - see below</li>
</ul>
<h3>Shutters</h3> 
<ul> 
    <li>Close</li> 
</ul>
<h3>Phone</h3> 
 <ul>
    <li>Unplug phone from socket</li> 
</ul>
<h3>Electricity</h3> 
<ul> 
    <li>Switch off</li> 
    <li>Take reading</li>
    <li>Remove all plugs</li>
</ul>
<h3>Keys</h3> 
<ul> 
    <li>One with Jehan Valette</li>
    <li>One hidden</li>
</ul>

<h2>Pool</h2>

<h3>Weekly clean</h3>
<ul>
	<li>Bottom of pool</li>
    <li>Liner at water level.</li>
    <li>Filter basket</li>
    <li>Filter - but perform several BACKWASH/RINSE cycles</li>
    <li>Leave the pump OFF</li>
</ul>

<h3>Steps</h3>
<ul>
    <li>Undo the bolts securing the steps.</li>
    <li>Clean the steps and store them.</li>
</ul>

<h3>Water in pool</h3>
<ul>
	<li>Do not drain off any water from the pool.</li>
	<li>Add enough anti-freeze for 50m3
</ul>

<h3>Plugs</h3>
<p>Note that this will have to be done under water!<p>
<ul>
	<li>Remove and store the jets from the inlets and use small plugs on inlets and on the vacuum outlet</li>
	<li>Remove and store the skimmer basket; insert the large bung into the skimmer outlet</li>
</ul>

<h3>Drain</h3>
<ul>
	<li>Open the SKIMMER, PRISE BALAI ASPIRATEUR, BONDE DE FOND and REFOULEMENT valves</li>
    <li>Open the filter basket cover. The pipes to the pool will drain into the pump house.</li>
    <li>Store the filter basket cover and basket</li>
	<li>Remove and store bottom plug of the sand filter to drain it</li>
	<li>Remove and store the top cover of the sand filter</li>
    <li>Remove and store the bottom plugs of the pump (two) to drain</li>
</ul>

<h3>Pump house</h3>
<ul>
    <li>Clean out debris and standing water</li>
    <li>Fill with as much bubble wrap as available</li>
</ul> 

<h3>Covers</h3> 
<ul>
    <li>Close the main cover and attach the clips</li>
    <li>Install the net using metal stakes and elastics</li>
	<ul>
		<li>start with middle pegs at one end</li>
		<li>move down pool doing the occasional peg on both sides</li>
		<li>do middle pegs at other end</li>
		<li>finally do corners</li>
    </ul>
    <li>Store the key for the cover behind the main front door</li>
</ul>
<h3>Power</h3>
<ul>
	<li>Cut power at distribution board in Salon</li>
</ul>

<h2>Draining the plumbing</h2>
<p>Do all the following - about half an hour of work. To re-fill the system, after the winter, it is generally necessary to reverse each of these stages, and then to open each tap to let out trapped air, until the water runs freely…then, finally, to close the chauffeau fuses on the main fuse box.
</p>

<ol>
    <li>Chauffeau fuses:
        <ul>
            <li>Ensure that the chauffeau fuses on the main fuse box are in the open position.</li>
        </ul>
    </li>

	<li>Main stop cock:
        <ul>
            <li>Turn off the main stop cock next to the meter, outside the front door (Tap handle will then be at right angles to the line of the water pipe).</li>
            <li>Ensure there is insulation covering the water meter.</li>
        </ul>
    </li>

	<li>Behind the house:
		<ul>
			<li>Turn on the outside tap.</li>
        	<li>Open the mixer tap.</li>
            <li>Open both taps on the main shower column</li>
            <li>Unscrew the bottom of the flexible hose</li>
        	<li>Loosen the brass drain cock at the bottom of the pipe on your left.</li>
		</ul>
	</li>

	<li>Kitchen:
		<ul>
			<li>Turn on the sink tap (Set it to the middle, so both hot and cold are on).</li>
            <li>Turn on the washing-up machine tap (Right hand side, below the sink). This will release water, so put a bowl beneath it, first.</li>
            <li>Disconnect the flexible pipe to the washing machine (unscrew the blue collar ant-clockwise).</li>
            <li>Turn on the washing machine tap. This will release water, so catch it in a mug.</li>
            <li>Ditto for the dishwasher</li>
        </ul>     
    </li>

	<li>Main shower room:
		<ul>
			<li>Flush the loo.
            <li>Open basin tap … keep it in the middle to open both hot and cold.</li>
            <li>Place shower head on the floor of the shower, then open the shower tap, again at the central position.</li>
        </ul>
    </li>

	<li> Bathroom en-suite to guest bedroom:
		<ul>
			<li>Flush the loo.</li>
            <li>Turn on hot and cold bath and basin  taps.</li>
            <li>Turn on both bidet taps.</li>
            <li>Drain the chauffeau by turning the red knob one click anti-clockwise…this can be left to drain in it’s own time (Approx 15 minutes)</li>
        </ul>
    </li>

    <li> Salon, above window on the right as you enter:
        <ul>
            <li>Remove segments from the ceiling.</li>
            <li>Open drain cocks and catch water.</li>
        </ul>
    </li>

    <li>Main sitting room, behind the front door:
    	<ul>
    		<li>Raise electrical items off the floor.</li>
            <li>Ensure the tap on the top, on the right (The big one) is open … i.e. turned fully anticlockwise. This is good for all the year.</li>
            <li>Open the horizontal drain cock on the left, slowly, and catch the water which will run out….probably 3+ saucepans full.  Leave it open, with a pan beneath to catch drips which will continue for an hour or so.</li>
        </ul>
    </li>

    <li>Finally:  Pour a little car antifreeze into each plug hole:
    	<ul>
            <li>Kitchen sink</li>
            <li>Shower</li>
            <li>Bath</li>
            <li>Bidet</li>
            <li>Both wash basins on the top floor</li>
            <li>The two loos (the bowls and the cisterns)</li>
        </ul>
    </li>
    <li>Remember !….
    	<ul>
    		<li>Andy can blow the system clear with compressed air …. That extracts a good few saucepans full</li>
    		<li>When re-filling the system, check that each stage has been dealt with. A loose drainage point will cause a minor flood ……..!</li>
    	</ul>
    </li>
   </ol>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<%= render 'layouts/print' %> 
<p>
<h2>Jim and Alex Hunter</h2>
</p>
<p>
14 Caledonian Place<br>
ABERDEEN<br>
AB11 6TT<br>
UK<br>
<em>Phone</em> (+44) 01224 582 669
</p>
<p>
Lacaze<br>
Toulonjac<br>
12200 VILLEFRANCHE-DE-ROUERGUE<br>
FRANCE<br>
<em>Phone</em> (+33) 05 65 45 19 11
</p>
<h2>Jim</h2>
<em>Mobile</em> (+44) 07724 056 224<br>
<em>email</em> j.hunter@abdn.ac.uk
</p>
<h2>Alex</h2>
<em>Mobile</em> (+44) 07746 776 143<br>
<em>email</em> alexchunter@hotmail.com
</p>

app/views/static_pages/directions.html.erb
<% provide(:title, 'Directions') %>
<h1>Directions</h1>
<%= render 'layouts/print' %> 
<p>
The nearest large town is <strong>Villefranche-de-Rouergues</strong> in the <strong>Aveyron</strong> department.
</p>
<h2>From Toulouse</h2>
<p>
The easiest airport to fly to is <strong>Toulouse</strong>, with flights from London (BA and Easyjet), Paris, Frankfurt, Istanbul(!), etc. and (in the summer) Edinburgh (Jet2.com). You should allow 1½ to 2 hours to drive to the house from Toulouse Airport. 
</p>
<p>
On exiting the airport, follow signs for <strong>Toulouse</strong> until you see signs to the <strong>Bordeaux/Paris</strong> autoroute. Once on the main autoroute, you will need to take a ticket at the Peage. There are two sections where you need to pay; you pay on leaving the section (see below). When the autoroute splits, follow the signs for <strong>Paris/Montaubon</strong> (not Bordeaux) and continue to Causade. Leave the autoroute at <strong>Caussade</strong> and take signs for <strong>Villefranche</strong> via <strong>Caylus</strong> on the <strong>D926</strong>. It's a good road, very straight, but there are speed traps so be careful. At the departmental boundary into the Aveyron the road becomes the <strong>D1</strong>. At the first main roundabout, remain on the D1; do not take the road signed into Villefranche, but keep going straight ahead (signed for <strong>Rodez</strong>). Shortly after, take the first exit for the <strong>D24</strong> and <strong>Cajarc/Toulonjac</strong>. Coming off the slip road turn left - not right into Villefranche - and enter <strong>Toulonjac</strong>.
<p>
<strong>Cost of autoroute tolls</strong>: 
<ul>
<li>Toulouse northwards: 2.50 euros</li>
<li>Montaubon to Caussade: 1.40 euros</li>
</ul>
<p>Change is given; you can also use a credit card.</p>
</p>
<h2>From Toulonjac</h2>
<p>Continue through the village, with the bar/restaurant (Le Claux de Belvezet) on your left. Soon after a left-hand bend and the sign marking the end of the village, take the first small road on the <strong>right</strong> signed <strong>Lacaze</strong> and marked with a 'No Through Road' sign. Take the first turning on the left - our house is immediately on your right. If you miss the road off the main road, take the next one on the right about 100 m later (signed La Caze). This will bring you in about 200 m to the T junction described above - our house is on the left before the junction.
</p>
<h2>From Rodez</h2>
<p>
There are Ryanair flights from Stansted to Rodez which is about 45 minutes to the east of Toulonjac. Take signs to <strong>Rodez</strong> and then to <strong>Rignac/Villefranche/Montaubon</strong>. Approaching Villefranche on the D1 from the east, ignore the first exit to Villefranche but continue to the second exit and follow the signs for the <strong>D24</strong> and <strong>Cajarc/Toulonjac</strong>. Coming off the slip road turn left - not right into Villefranche - and enter <strong>Toulonjac</strong>. See directions from Toulonjac above.
</p>
<h2>From the A20</h2>
<p>
If you're coming from the north, the best approach is probably down the <strong>A20</strong> autoroute (Paris/Orleans/Vierzon/Limoges). We normally turn off at <strong>Exit 56</strong> south of <strong>Brive</strong> and take the <strong>D802</strong> to <strong>Figeac</strong>. Go round the Figeac bypass and then take the <strong>D922</strong> signed for <strong>Villeneuve</strong> and <strong>Villefranche</strong>. We normally cut across minor roads from Villeneuve to Lacaze, but it's simpler to carry on towards Villefranche until you meet the <strong>D1</strong> (see above dirctions from Rodez) at which point you go towards <strong>Caussade</strong> before taking signs for the <strong>D24</strong> and <strong>Cajarc/Toulonjac</strong>.  Coming off the slip road, turn <strong>left</strong> - not right into Villefranche - and enter <strong>Toulonjac</strong>. See directions from Toulonjac above.
</p>
<h2>Sunday arrivals</h2>
<p>
If you are arriving on a Sunday, note that the only food shop open in the area closes at lunch time. However the first service station on the autoroute from Toulouse sells bread, milk etc.
</p>


app/views/static_pages/help.html.erb
<% provide(:title, 'HELP') %>
<h1>HELP</h1>
<%= render 'layouts/print' %> 
<p>
The following people can be approached in an emergency:
<ul>
<li><strong>Neighbours</strong> – Bill and Joan Timm (English) – turn right out of our front door and they are the nearest house past our post box (summer visitors like us).</li>
<li><strong>Neighbours</strong> - Jehan and Suzette Valette (French) – turn left out of the front door and left up the hill at the end of our garden. First house on the right with blue shutters (permanent residents).</li>
<li><strong>Builder</strong> – Andy Low (English) – lives about 20 minutes drive away but is happy to deal with things by phone (and to come over if need be): Home: 05 65 24 95 48;  mobile 06 87 03 82 75
<li><strong>Pool</strong> – Chris Grundy (English) – ditto – mobile 06 21 58 44 53</li>
</ul>
</p>

app/views/static_pages/home.html.erb
<div class="center">
   <div class="hero-unit">  
   	   <h1>Lacaze</h1>
   </div>
   <%= image_tag("lacaze_front.JPG", alt: "Lacaze", width: "667", height: "500") %>
</div>

app/views/static_pages/photos.html.erb
<% provide(:title, 'Photos') %>
<h1>Photos</h1>
<%= image_tag("lacaze_front.JPG", alt: "Lacaze") %>
<p>The front</p>
<%= image_tag("lacaze_pool.JPG", alt: "Pool") %>
<p>The pool</p>

app/views/static_pages/taxis.html.erb
<% provide(:title, 'Taxis') %>
<h1>Taxis</h1>

<%= render 'layouts/print' %> 

<p>We have used, and recommend, Sylvie Mahe - who speaks English.
<ul>
<li>MAHE: 06 73 33 33 73</li>
</ul>
</p>
<p>
Others listed are:
<ul>
<li>Michel DOURNES: 06 08 97 30 (mob 06 72 16 04 22)</li>
<li>FREYSSINET: 05 08 97 35 30</li>
<li>LACASSAGNE:	05 65 81 10 10</li>
<li>H VILLEFRANCHOIS: 05 65 45 60 60</li>
<li>XAVIER: 06 03 13 48 46</li>
<li>RAYNAL: 06 19 69 11 11</li>
<li>D'MARTIEL: 06 73 67 25 00</li>
</ul>
</p>


app/views/static_pages/things_to_do.html.erb
<% provide(:title, 'Things to do') %>
<h1>Things to do</h1>

<%= render 'layouts/print' %> 

<h2>Eating</h2>
<p>The restaurant in Toulonjac is great for lunchtime - very friendly patron. During the week there is a fixed menu at a very reasonable price. You can walk home if need be!
</p>
<p>
In Villefranche, try the Globe brasserie for lunches near the river. Also the Univers Hotel restaurant has been recently revamped under an award-winning young chef. We have also eaten at the Bistro, very well and very cheaply; the patrons are keen walkers and very nice.
</p>
<p>
For fine lunching/dining try the Relais de Farrou. For an even better (and more expensive) meal, book ahead at the Vieux Pont, Belcastel.
</p>
<h2>Visiting</h2>
<p>There is a selection of maps and guides in the house for the area – help yourselves.
</p>
<p>
Good places to visit:
<ul>
	<li>Figeac – lovely town</li>
	<li>Albi – ditto, plus Toulouse Lautrec art gallery</li>
	<li>Cajarc – on the Lot river</li>
	<li>Najac</li>
	<li>Villeneuve</li>
	<li>Peyrusse le Roc</li>
	<li>Conques</li>
	<li>Canoing down the Gorges de l'Aveyron - start from Najac or from St Antonin Noble Val
</ul
</p>

